export const novadefiAbi = [
  {
    "inputs":[{"internalType":"address","name":"_user","type":"address"}],
    "name":"getPendingRewards",
    "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[],
    "name":"totalInvested",
    "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[],
    "name":"treasury",
    "outputs":[{"internalType":"address","name":"","type":"address"}],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[{"internalType":"address","name":"","type":"address"}],
    "name":"users",
    "outputs":[
      {"internalType":"uint256","name":"depositAmt","type":"uint256"},
      {"internalType":"uint256","name":"rewardBalance","type":"uint256"},
      {"internalType":"uint256","name":"lastUpdate","type":"uint256"},
      {"internalType":"uint256","name":"totalWithdrawn","type":"uint256"},
      {"internalType":"uint256","name":"monthlyWithdrawn","type":"uint256"},
      {"internalType":"uint256","name":"lastMonthReset","type":"uint256"},
      {"internalType":"address","name":"referrer","type":"address"},
      {"internalType":"uint8","name":"level","type":"uint8"},
      {"internalType":"uint256","name":"teamCountL3","type":"uint256"},
      {"internalType":"uint256","name":"lastSalaryTeamSnapshot","type":"uint256"},
      {"internalType":"uint256","name":"depositTime","type":"uint256"},
      {"internalType":"bool","name":"exists","type":"bool"}
    ],
    "stateMutability":"view",
    "type":"function"
  }
]